export const LOGIN = '/dashboard/auth/'
export const OTP = '/dashboard/auth/otp'
export const SIGNUP = '/dashboard/auth/sign-up'
export const NEW_PASSWORD = '/dashboard/auth/new-password'
export const NEW_PASSWORD_CONFIRMED = '/dashboard/auth/new-password-confirmed'
export const ACCOUNT_UNBLOCK = '/dashboard/auth/account-unlock'
export const PASSWORD_RESET = '/dashboard/auth/password-reset'
export const SUSPENDED_BY_PLATFORM = '/dashboard/auth/suspended-by-platform'
export const CONFIRM_CURRENT_EMAIL = '/dashboard/auth/confirm-current-email'
export const CONFIRM_NEW_EMAIL = '/dashboard/auth/confirm-new-email'

export const ONBOARDING = '/dashboard/onboarding'
export const ERROR_PAGE = '/dashboard/home/error404'
export const USER_PROFILE = '/dashboard/home/user-profile'
export const COMPANY_PROFILE = '/dashboard/home/company-profile'
export const ENGINEERING_IN_PROCESS = '/dashboard/home/in-progress'
